#!/bin/bash
# Set GAMEDIR to the current directory and set logfile
GAMEDIR="$PWD"
LOGFILE="$GAMEDIR/patchlog.txt"

# Redirect output and error to the log file
exec > >(tee -a "$LOGFILE") 2>&1
echo "GAMEDIR is set to: $GAMEDIR"

# Exports
export DATADIR="$GAMEDIR/assets"
export DATAFILE="soniccolors.port"
export LD_LIBRARY_PATH="/usr/lib:$GAMEDIR/lib:$GAMEDIR/tools/libs:$LD_LIBRARY_PATH"
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
export TOOLDIR="$GAMEDIR/tools"
export TMPDIR="$GAMEDIR/tmp"
export PATH="$GAMEDIR/tools:$PATH"

# Permissions
chmod 666 /dev/uinput
chmod 777 "$TOOLDIR/gmKtool.py"
chmod 777 "$TOOLDIR/oggenc"

cd "$GAMEDIR"

unzip_patch() {
    echo "Unzipping the patch file..."
    if [ -f "./tools/patches/soniccolors.zip.001" ]; then
        if [ -x "$(command -v 7z)" ]; then
            ./tools/7za x ./tools/patches/soniccolors.zip.001 -o./tools/patches
            if [ $? -eq 0 ]; then
                echo "Patch file successfully extracted."
                rm ./tools/patches/soniccolors.zip.*
            else
                echo "Failed to extract multi-part archive."
                exit 1
            fi
        else
            echo "7za tool is not available. Failed to extract xdelta patch."
            exit 1
        fi
    else
        echo "Patch archive not found!"
        exit 1
    fi
}

apply_xdelta() {
    # Check if the data.win file exists and apply xdelta
    if [ -f "$DATADIR/data.win" ]; then
        # v0.4.1
        output=$($controlfolder/xdelta3 -d -s "$DATADIR/data.win" -f "./tools/patches/soniccolors.xdelta" "$DATADIR/game.droid" 2>&1)
        if [ $? -eq 0 ]; then
            echo "Patch applied successfully"
            echo "$output"
            rm "$DATADIR/data.win"
        else
            echo "Failed to apply patch"
            echo "$output"
            exit 1
        fi
    else
        echo "No data.win file found to patch!"
        sleep 2
        rm -rf patchlog.txt
        exit 1
    fi
}

compress_audio() {
    mkdir -p "$TMPDIR"

    # Run the compression tool
    PYTHON=$(which python3)
    echo "Running GMTools on data and audiogroups."
    $PYTHON ./tools/gmKtool.py -vv -D -R 22050 -m 0 -r -b 32 -d "$TMPDIR" "$DATADIR/game.droid"

    if [ $? -eq 0 ]; then
        echo "Compression completed successfully."
        mv "$TMPDIR/"* "$DATADIR"
        echo "Moved compressed files to $DATADIR."
        rmdir "$TMPDIR"
        echo "Temporary directory $TMPDIR removed."
        echo "Audio compression applied successfully."
    else
        echo "Audio compression failed."
        echo "Cleaning up temporary directory $TMPDIR."
        rm -rf "$TMPDIR"
    fi
}

zip_archive() {
        zip -r -0 $DATAFILE ./assets/
        rm -rf ./assets
        mkdir -p saves
}

# Use move_data function while the game is fairly new and is receiving several updates.
move_data() {
    mkdir -p saves
    mv -f ./assets/* ./saves
    echo "Moved game assets to saves directory."
}

process_game() {
    # Delete unnecessary files
    rm -rf $DATADIR/*.exe $DATADIR/.gitkeep
    echo "Removed unnecessary files"

    echo "Unpacking xdelta patch..."
    unzip_patch
    sleep 1
    echo "Applying xdelta patch"
    apply_xdelta
    sleep 1
    echo "Compressing audio..."
    compress_audio
    sleep 1
    echo "Finishing up..."
    zip_archive
    sleep 1
	
    # Final completion message
    echo "Patching process complete!"
}

# Call the function
process_game